production:
  services:
    web:
      image: quay.io/cloud66/sample-rails
      command: rackup -p 3000
      build_command: rake db:migrate
      deploy_command: rake db:migrate
      log_folder: /usr/src/app/log
      local_ports: [3000]
      public_port: "8080"
  databases:
    - "mysql"
