production:
  services:
    web:
      image: quay.io/cloud66/sample-rails
      command: rackup -p 3000
      build_command: rake db:migrate
      deploy_command: rake db:migrate
      log_folder: /usr/src/app/log
      ports: ["3000:80:443"]
      volumes: ["/tmp:container/tmp_host"]
      restart_on_redeploy: true
  databases:
    - "mysql"
